COUNTRY_CODES = [
    {"code": "+93", "name": "Afghanistan", "number_length": 9, "places": ["Kabul", "Kandahar", "Herat"]},
    {"code": "+355", "name": "Albania", "number_length": 9, "places": ["Tirana", "Durres", "Vlorë"]},
    {"code": "+213", "name": "Algeria", "number_length": 9, "places": ["Algiers", "Oran", "Constantine"]},
    {"code": "+376", "name": "Andorra", "number_length": 6, "places": ["Andorra la Vella", "Escaldes-Engordany"]},
    {"code": "+244", "name": "Angola", "number_length": 9, "places": ["Luanda", "N'dalatando", "Huambo"]},
    {"code": "+1", "name": "United States", "number_length": 10, "places": ["New York", "Los Angeles", "Chicago"]},
    {"code": "+973", "name": "Bahrain", "number_length": 8, "places": ["Manama", "Riffa", "Muharraq"]},
    {"code": "+880", "name": "Bangladesh", "number_length": 10, "places": ["Dhaka", "Chittagong", "Khulna"]},
    {"code": "+375", "name": "Belarus", "number_length": 9, "places": ["Minsk", "Gomel", "Mogilev"]},
    {"code": "+32", "name": "Belgium", "number_length": 9, "places": ["Brussels", "Antwerp", "Ghent"]},
    {"code": "+501", "name": "Belize", "number_length": 7, "places": ["Belize City", "Belmopan"]},
    {"code": "+229", "name": "Benin", "number_length": 8, "places": ["Porto-Novo", "Cotonou"]},
    {"code": "+975", "name": "Bhutan", "number_length": 8, "places": ["Thimphu", "Paro"]},
    {"code": "+591", "name": "Bolivia", "number_length": 8, "places": ["La Paz", "Santa Cruz", "Cochabamba"]},
    {"code": "+267", "name": "Botswana", "number_length": 8, "places": ["Gaborone", "Francistown", "Maun"]},
    {"code": "+55", "name": "Brazil", "number_length": 10, "places": ["Sao Paulo", "Rio de Janeiro", "Brasilia"]},
    {"code": "+673", "name": "Brunei", "number_length": 7, "places": ["Bandar Seri Begawan"]},
    {"code": "+359", "name": "Bulgaria", "number_length": 9, "places": ["Sofia", "Plovdiv", "Varna"]},
    {"code": "+226", "name": "Burkina Faso", "number_length": 8, "places": ["Ouagadougou", "Bobo-Dioulasso"]},
    {"code": "+257", "name": "Burundi", "number_length": 8, "places": ["Bujumbura", "Gitega"]},
    {"code": "+855", "name": "Cambodia", "number_length": 9, "places": ["Phnom Penh", "Siem Reap", "Battambang"]},
    {"code": "+237", "name": "Cameroon", "number_length": 9, "places": ["Yaoundé", "Douala", "Garoua"]},
    {"code": "+1", "name": "Canada", "number_length": 10, "places": ["Toronto", "Vancouver", "Montreal"]},
    {"code": "+238", "name": "Cape Verde", "number_length": 7, "places": ["Praia", "Mindelo"]},
    {"code": "+236", "name": "Central African Republic", "number_length": 8, "places": ["Bangui"]},
    {"code": "+235", "name": "Chad", "number_length": 8, "places": ["N'Djamena"]},
    {"code": "+56", "name": "Chile", "number_length": 9, "places": ["Santiago", "Valparaiso", "Concepcion"]},
    {"code": "+86", "name": "China", "number_length": 11, "places": ["Beijing", "Shanghai", "Guangzhou"]},
    {"code": "+61", "name": "Australia", "number_length": 9, "places": ["Sydney", "Melbourne", "Brisbane"]},
    {"code": "+243", "name": "Democratic Republic of the Congo", "number_length": 9, "places": ["Kinshasa", "Lubumbashi"]},
    {"code": "+242", "name": "Republic of the Congo", "number_length": 9, "places": ["Brazzaville", "Pointe-Noire"]},
    {"code": "+45", "name": "Denmark", "number_length": 8, "places": ["Copenhagen", "Aarhus", "Odense"]},
    {"code": "+253", "name": "Djibouti", "number_length": 8, "places": ["Djibouti City"]},
    {"code": "+1767", "name": "Dominica", "number_length": 7, "places": ["Roseau", "Portsmouth"]},
    {"code": "+1", "name": "Dominican Republic", "number_length": 10, "places": ["Santo Domingo", "Santiago"]},
    {"code": "+593", "name": "Ecuador", "number_length": 9, "places": ["Quito", "Guayaquil"]},
    {"code": "+20", "name": "Egypt", "number_length": 10, "places": ["Cairo", "Alexandria", "Giza"]},
    {"code": "+503", "name": "El Salvador", "number_length": 8, "places": ["San Salvador", "Santa Ana"]},
    {"code": "+240", "name": "Equatorial Guinea", "number_length": 9, "places": ["Malabo", "Bata"]},
    {"code": "+291", "name": "Eritrea", "number_length": 7, "places": ["Asmara"]},
    {"code": "+372", "name": "Estonia", "number_length": 7, "places": ["Tallinn", "Tartu"]},
    {"code": "+251", "name": "Ethiopia", "number_length": 9, "places": ["Addis Ababa", "Dire Dawa", "Mekelle"]},
    {"code": "+298", "name": "Faroe Islands", "number_length": 6, "places": ["Tórshavn", "Klaksvík"]},
    {"code": "+679", "name": "Fiji", "number_length": 7, "places": ["Suva", "Nadi", "Lautoka"]},
    {"code": "+358", "name": "Finland", "number_length": 9, "places": ["Helsinki", "Espoo", "Tampere"]},
    {"code": "+33", "name": "France", "number_length": 9, "places": ["Paris", "Marseille", "Lyon"]},
    {"code": "+241", "name": "Gabon", "number_length": 9, "places": ["Libreville", "Port-Gentil"]},
    {"code": "+220", "name": "Gambia", "number_length": 7, "places": ["Banjul", "Serekunda"]},
    {"code": "+995", "name": "Georgia", "number_length": 9, "places": ["Tbilisi", "Batumi", "Kutaisi"]},
    {"code": "+49", "name": "Germany", "number_length": 11, "places": ["Berlin", "Munich", "Hamburg"]},
    {"code": "+233", "name": "Ghana", "number_length": 9, "places": ["Accra", "Kumasi", "Tamale"]},
    {"code": "+30", "name": "Greece", "number_length": 10, "places": ["Athens", "Thessaloniki", "Patras"]},
    {"code": "+502", "name": "Guatemala", "number_length": 8, "places": ["Guatemala City", "Quetzaltenango"]},
    {"code": "+224", "name": "Guinea", "number_length": 8, "places": ["Conakry", "Nzérékoré"]},
    {"code": "+245", "name": "Guinea-Bissau", "number_length": 7, "places": ["Bissau"]},
    {"code": "+592", "name": "Guyana", "number_length": 7, "places": ["Georgetown"]},
    {"code": "+509", "name": "Haiti", "number_length": 8, "places": ["Port-au-Prince", "Cap-Haïtien"]},
    {"code": "+504", "name": "Honduras", "number_length": 8, "places": ["Tegucigalpa", "San Pedro Sula"]},
    {"code": "+36", "name": "Hungary", "number_length": 9, "places": ["Budapest", "Debrecen", "Szeged"]},
    {"code": "+354", "name": "Iceland", "number_length": 7, "places": ["Reykjavik", "Akureyri"]},
    {"code": "+91", "name": "India", "number_length": 10, "places": ["Delhi", "Mumbai", "Bangalore"]},
    {"code": "+62", "name": "Indonesia", "number_length": 10, "places": ["Jakarta", "Bali", "Surabaya"]},
    {"code": "+98", "name": "Iran", "number_length": 10, "places": ["Tehran", "Mashhad", "Isfahan"]},
    {"code": "+964", "name": "Iraq", "number_length": 10, "places": ["Baghdad", "Basra", "Mosul"]},
    {"code": "+353", "name": "Ireland", "number_length": 9, "places": ["Dublin", "Cork", "Galway"]},
    {"code": "+972", "name": "Israel", "number_length": 9, "places": ["Tel Aviv", "Jerusalem", "Haifa"]},
    {"code": "+39", "name": "Italy", "number_length": 10, "places": ["Rome", "Milan", "Naples"]},
    {"code": "+63", "name": "Philippines", "number_length": 10, "places": ["Manila", "Cebu", "Davao"]}
]
